filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/transcript/failed_schema/*.log*
      - /logs/transcript/schema_mismatch_masked/*.log*
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      index_name: "zolver-schema"
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /logs/transcript/transcript_val/*.log*
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      index_name: "zolver-val"
    fields_under_root: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "zolver-schema-%{+yyyy.MM.dd}"
      when.equals:
        index_name: "zolver-schema"
    - index: "zolver-val-%{+yyyy.MM.dd}"
      when.equals:
        index_name: "zolver-val"

setup.kibana:
  host: "kibana:5601"